"""Initial migration

Revision ID: 0bcc448faf90
Revises: 
Create Date: 2023-11-22 12:12:33.802896

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0bcc448faf90'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('org',
                    sa.Column('name', sa.String(length=30), nullable=False),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('org_user',
                    sa.Column('user_id', sa.UUID(), nullable=True),
                    sa.Column('org_id', sa.UUID(), nullable=False),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('org_user')
    op.drop_table('org')
    # ### end Alembic commands ###
