"""Add NOT NULL constraint to org_user.user_id

Revision ID: 18fed4238cff
Revises: be7b7e0f4f80
Create Date: 2023-12-16 19:49:15.213129

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '18fed4238cff'
down_revision: Union[str, None] = 'be7b7e0f4f80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('org_user', 'user_id',
                    existing_type=sa.UUID(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('org_user', 'user_id',
                    existing_type=sa.UUID(),
                    nullable=True)
    # ### end Alembic commands ###
