"""Add Chat history

Revision ID: 4348dafca633
Revises: 6b9f9bb5e52b
Create Date: 2024-01-06 12:35:35.648171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4348dafca633'
down_revision: Union[str, None] = '6b9f9bb5e52b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('message',
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.String(length=1024), nullable=False),
    sa.Column('author', sa.String(length=1024), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['public.chat.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.drop_constraint('chunk_org_id_fkey', 'chunk', type_='foreignkey')
    op.create_foreign_key(None, 'chunk', 'org', ['org_id'], ['id'], referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('org_user_user_id_fkey', 'org_user', type_='foreignkey')
    op.drop_constraint('org_user_org_id_fkey', 'org_user', type_='foreignkey')
    op.create_foreign_key(None, 'org_user', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='auth', ondelete='CASCADE')
    op.create_foreign_key(None, 'org_user', 'org', ['org_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'org_user', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'org_user', schema='public', type_='foreignkey')
    op.create_foreign_key('org_user_org_id_fkey', 'org_user', 'org', ['org_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('org_user_user_id_fkey', 'org_user', 'users', ['user_id'], ['id'], referent_schema='auth', ondelete='CASCADE')
    op.drop_constraint(None, 'chunk', type_='foreignkey')
    op.create_foreign_key('chunk_org_id_fkey', 'chunk', 'org', ['org_id'], ['id'], ondelete='CASCADE')
    op.drop_table('message', schema='public')
    op.drop_table('chat', schema='public')
    # ### end Alembic commands ###
