"""Update Foreign Keys

It's an Alembic thing, the code hasn't changed.

Revision ID: 75477fd03593
Revises: 6b9f9bb5e52b
Create Date: 2024-01-06 12:39:19.177967

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '75477fd03593'
down_revision: Union[str, None] = '6b9f9bb5e52b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chunk_org_id_fkey', 'chunk', type_='foreignkey')
    op.create_foreign_key(None, 'chunk', 'org', ['org_id'], ['id'], referent_schema='public',
                          ondelete='CASCADE')
    op.drop_constraint('org_user_org_id_fkey', 'org_user', type_='foreignkey')
    op.drop_constraint('org_user_user_id_fkey', 'org_user', type_='foreignkey')
    op.create_foreign_key(None, 'org_user', 'users', ['user_id'], ['id'], source_schema='public',
                          referent_schema='auth', ondelete='CASCADE')
    op.create_foreign_key(None, 'org_user', 'org', ['org_id'], ['id'], source_schema='public',
                          referent_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'org_user', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'org_user', schema='public', type_='foreignkey')
    op.create_foreign_key('org_user_user_id_fkey', 'org_user', 'users', ['user_id'], ['id'],
                          referent_schema='auth', ondelete='CASCADE')
    op.create_foreign_key('org_user_org_id_fkey', 'org_user', 'org', ['org_id'], ['id'],
                          ondelete='CASCADE')
    op.drop_constraint(None, 'chunk', type_='foreignkey')
    op.create_foreign_key('chunk_org_id_fkey', 'chunk', 'org', ['org_id'], ['id'],
                          ondelete='CASCADE')
    # ### end Alembic commands ###
