"""Add Metadata JSON field

Revision ID: cfe51dcc53f4
Revises: aaa5e8ba3992
Create Date: 2023-11-24 13:44:15.879174

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cfe51dcc53f4'
down_revision: Union[str, None] = 'aaa5e8ba3992'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunk', sa.Column('meta_data', postgresql.JSON(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chunk', 'meta_data')
    # ### end Alembic commands ###
