"""Converge chunk data into a single JSON column.

Revision ID: 3976b0447a9f
Revises: 40744628db97
Create Date: 2023-11-25 15:10:34.664861

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3976b0447a9f'
down_revision: Union[str, None] = '40744628db97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunk', sa.Column('data', postgresql.JSON(astext_type=sa.Text()), nullable=False))
    op.drop_column('chunk', 'text')
    op.drop_column('chunk', 'meta_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunk',
                  sa.Column('meta_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('chunk', sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('chunk', 'data')
    # ### end Alembic commands ###
