"""Add CASCADE on delete for org_id in Chunk and OrgUser

Revision ID: 40744628db97
Revises: cfe51dcc53f4
Create Date: 2023-11-25 13:23:47.536847

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '40744628db97'
down_revision: Union[str, None] = 'cfe51dcc53f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chunk_org_id_fkey', 'chunk', type_='foreignkey')
    op.create_foreign_key(None, 'chunk', 'org', ['org_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('org_user_org_id_fkey', 'org_user', type_='foreignkey')
    op.drop_constraint('org_user_user_id_fkey', 'org_user', type_='foreignkey')
    op.create_foreign_key(None, 'org_user', 'org', ['org_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'org_user', 'users', ['user_id'], ['id'], referent_schema='auth', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'org_user', type_='foreignkey')
    op.drop_constraint(None, 'org_user', type_='foreignkey')
    op.create_foreign_key('org_user_user_id_fkey', 'org_user', 'users', ['user_id'], ['id'], referent_schema='auth')
    op.create_foreign_key('org_user_org_id_fkey', 'org_user', 'org', ['org_id'], ['id'])
    op.drop_constraint(None, 'chunk', type_='foreignkey')
    op.create_foreign_key('chunk_org_id_fkey', 'chunk', 'org', ['org_id'], ['id'])
    # ### end Alembic commands ###
