"""Add Hash column to Chunk

Revision ID: be7b7e0f4f80
Revises: 3976b0447a9f
Create Date: 2023-11-27 12:25:42.295990

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'be7b7e0f4f80'
down_revision: Union[str, None] = '3976b0447a9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunk', sa.Column('hash_value', sa.String(length=64), nullable=False))
    op.drop_constraint('org_embedding_unique_together', 'chunk', type_='unique')
    op.create_unique_constraint('org_hash_unique_together', 'chunk', ['org_id', 'hash_value'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('org_hash_unique_together', 'chunk', type_='unique')
    op.create_unique_constraint('org_embedding_unique_together', 'chunk', ['org_id', 'embedding'])
    op.drop_column('chunk', 'hash_value')
    # ### end Alembic commands ###
