AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  API stack for working with LLM capabilities of REsolution Bot.

  REsolution API

Globals: # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-template-anatomy-globals.html
  Function:
    Timeout: 300
    MemorySize: 1024
    Tracing: Active
    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowOrigin: "'*'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowCredentials: "'*'"

Resources:
  APIHandler:
    Type: AWS::Serverless::Function     # More info about Function Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
    Properties:
      PackageType: Image
      CodeUri: ../server/
      Description: Main API entrypoint
      Architectures:
        - x86_64
      Tracing: Active
      AutoPublishAlias: live
      DeploymentPreference:
        Type: AllAtOnce
      ProvisionedConcurrencyConfig:
        ProvisionedConcurrentExecutions: 1
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: "arn:aws:secretsmanager:us-east-1:375747807787:secret:prod/SQLALCHEMY_DATABASE_URI-Tnq04k"
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: "arn:aws:secretsmanager:us-east-1:375747807787:secret:prod/OPENAI_API_KEY-T8Foxj"
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: "arn:aws:secretsmanager:us-east-1:375747807787:secret:prod/SUPABASE_KEY-UoHnHj"
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: "arn:aws:secretsmanager:us-east-1:375747807787:secret:prod/SUPABASE_URL-1ZGSwe"
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: "arn:aws:secretsmanager:us-east-1:375747807787:secret:prod/OPENAI_API_KEY-T8Foxj"
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: "arn:aws:secretsmanager:us-east-1:375747807787:secret:prod/JWT_SECRET_KEY-mO7PzQ"
      Events:
        CreateChatPath:
          Type: Api           # More info about API Event Source: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-api.html
          Properties:
            Path: /chats
            Method: POST
        SendMessagePath:
          Type: Api
          Properties:
            Path: /messages
            Method: POST
        ### temp endpoints to stub QuivrUI
        GetChatsPath:
          Type: Api
          Properties:
            Path: /chats
            Method: GET
        GetBrainsPath:
          Type: Api
          Properties:
            Path: /brains
            Method: GET
        GetDefaultBrainPath:
          Type: Api
          Properties:
            Path: /brains/default
            Method: GET
        GetOnboardingPath:
          Type: Api
          Properties:
            Path: /onboarding
            Method: GET
        GetPromptsPath:
          Type: Api
          Properties:
            Path: /prompts
            Method: GET
      # Powertools for AWS Lambda (Python) env vars: https://awslabs.github.io/aws-lambda-powertools-python/#environment-variables
      Environment:
        Variables:
          LOG_LEVEL: INFO
          JWT_SECRET_KEY: '{{resolve:secretsmanager:prod/JWT_SECRET_KEY}}'
          SUPABASE_URL: '{{resolve:secretsmanager:prod/SUPABASE_URL}}'
          SUPABASE_KEY: '{{resolve:secretsmanager:prod/SUPABASE_KEY}}'
          OPENAI_API_KEY: '{{resolve:secretsmanager:prod/OPENAI_API_KEY}}'
          SQLALCHEMY_DATABASE_URI: '{{resolve:secretsmanager:prod/SQLALCHEMY_DATABASE_URI}}'
          POWERTOOLS_SERVICE_NAME: APIHandler
          POWERTOOLS_METRICS_NAMESPACE: Powertools
      Tags:
        LambdaPowertools: python
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ../server/
      DockerTag: python3.11-v1
  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'

Outputs:
  REsolutionApi:
    Description: API Gateway endpoint URL for Prod environment for the Lambda Function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"

  LambdaFunction:
    Description: API monolith Lambda Function ARN
    Value: !GetAtt APIHandler.Arn
