#!/bin/bash

# Get the directory where the script is located
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
cd "$SCRIPT_DIR/../server" || exit

aws sso login --sso-session serge-guardian
aws ecr get-login-password --region us-east-1 --profile serge-guardian-admin | docker login --username AWS --password-stdin 375747807787.dkr.ecr.us-east-1.amazonaws.com
docker buildx build --platform linux/amd64,linux/arm64 --push -t 375747807787.dkr.ecr.us-east-1.amazonaws.com/resolution .
scp -i ~/.ssh/REsolution-API-EC2.pem ../.env.prod ec2-user@ec2-54-209-19-205.compute-1.amazonaws.com:/home/ec2-user/.env.prod
scp -i ~/.ssh/REsolution-API-EC2.pem "$SCRIPT_DIR/go" ec2-user@ec2-54-209-19-205.compute-1.amazonaws.com:/home/ec2-user/go
