"""Add Chunk

Revision ID: 1ab7085b663d
Revises: 1bc47b191673
Create Date: 2023-11-24 12:57:48.270502

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1ab7085b663d'
down_revision: Union[str, None] = '1bc47b191673'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('org_embedding_unique_together', 'chunk', ['org_id', 'embedding'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('org_embedding_unique_together', 'chunk', type_='unique')
    # ### end Alembic commands ###
