"""Add Chunk

Revision ID: 1bc47b191673
Revises: 0bcc448faf90
Create Date: 2023-11-22 12:52:54.545099

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '1bc47b191673'
down_revision: Union[str, None] = '0bcc448faf90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chunk',
                    sa.Column('org_id', sa.UUID(), nullable=False),
                    sa.Column('embedding', Vector(dim=1536), nullable=True),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chunk')
    # ### end Alembic commands ###
