"""Add Chunk

Revision ID: aaa5e8ba3992
Revises: 1ab7085b663d
Create Date: 2023-11-24 13:29:15.878595

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'aaa5e8ba3992'
down_revision: Union[str, None] = '1ab7085b663d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunk', sa.Column('text', sa.String(), nullable=False))
    op.alter_column('chunk', 'embedding', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chunk', 'embedding', nullable=True)
    op.drop_column('chunk', 'text')
    # ### end Alembic commands ###
