"""Unify base class

Revision ID: b678bc28fa38
Revises: ebffe6d40496
Create Date: 2023-11-20 13:38:59.598245

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b678bc28fa38'
down_revision: Union[str, None] = 'ebffe6d40496'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('org',
                    sa.Column('name', sa.String(length=30), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('org_user',
                    sa.Column('user_id', sa.UUID(), nullable=True),
                    sa.Column('org_id', sa.Integer(), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.drop_table('orgs_x_users')
    op.drop_table('orgs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orgs',
                    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('orgs_id_seq'::regclass)"),
                              autoincrement=True, nullable=False),
                    sa.Column('name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name='orgs_pkey'),
                    postgresql_ignore_search_path=False
                    )
    op.create_table('orgs_x_users',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
                    sa.Column('org_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], name='orgs_x_users_org_id_fkey'),
                    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name='orgs_x_users_user_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name='orgs_x_users_pkey')
                    )
    op.drop_table('org_user')
    op.drop_table('org')
    # ### end Alembic commands ###
