"""Initial migration

Revision ID: ebffe6d40496
Revises: 
Create Date: 2023-11-19 15:52:47.493479

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ebffe6d40496'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table('orgs',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=30), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('orgs_x_users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.UUID(), nullable=True),
                    sa.Column('org_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orgs_x_users')
    op.drop_table('orgs')
    op.drop_index('users_instance_id_idx', table_name='users', schema='auth', postgresql_include=[])
    op.drop_index('users_instance_id_email_idx', table_name='users', schema='auth', postgresql_include=[])
    op.drop_index('users_email_partial_key', table_name='users', schema='auth',
                  postgresql_where='(is_sso_user = false)', postgresql_include=[])
    op.drop_index('recovery_token_idx', table_name='users', schema='auth',
                  postgresql_where="((recovery_token)::text !~ '^[0-9 ]*$'::text)", postgresql_include=[])
    op.drop_index('reauthentication_token_idx', table_name='users', schema='auth',
                  postgresql_where="((reauthentication_token)::text !~ '^[0-9 ]*$'::text)", postgresql_include=[])
    op.drop_index('email_change_token_new_idx', table_name='users', schema='auth',
                  postgresql_where="((email_change_token_new)::text !~ '^[0-9 ]*$'::text)", postgresql_include=[])
    op.drop_index('email_change_token_current_idx', table_name='users', schema='auth',
                  postgresql_where="((email_change_token_current)::text !~ '^[0-9 ]*$'::text)", postgresql_include=[])
    op.drop_index('confirmation_token_idx', table_name='users', schema='auth',
                  postgresql_where="((confirmation_token)::text !~ '^[0-9 ]*$'::text)", postgresql_include=[])
    op.drop_table('users', schema='auth')
    # ### end Alembic commands ###
